### PR TITLE
Merging Updated Features from RRV1

### PR DESCRIPTION
**Pull request by ash-t-luu**
**Issue Type**

- [x] Bug
- [ ] Feature
- [ ] Tech Debt

**Description**
Creating a pull request to merge RecipeRouletteV1 DEV BRANCH to update RecipeRouletteV2 DEV BRANCH. Previously did not have the most recent updated project build.

### CODE REVIEW

**Review by basselfares — APPROVED** [review]

**Review by crispulum — APPROVED** [review]
LOOKS GOOD TO ME!!!!!
-AA

**Review by jonbingkim — APPROVED** [review]
LGTM!
-JK

**Review by crispulum — APPROVED** [review]
LGTM
AA

**Review by crispulum — APPROVED** [review]
looks good to me
aa

**Pull request merged**
